version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-client
    ports:
      - 8080:80

  nginx:
    image: nginx:alpine
    container_name: nginx-client
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app