services:
  api:
    build:
      context: ../sales-web-system-api
      dockerfile: Dockerfile
    image: sales-web-system-api-php8_2
    container_name: sales-web-system-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../sales-web-system-api:/var/www
    networks:
      - sales-web-system

  db:
    image: mysql:latest
    container_name: sales-web-system-db
    environment:
      MYSQL_DATABASE: sales_web_system
      MYSQL_ROOT_PASSWORD: sales_web_system
      MYSQL_PASSWORD: sales_web_system
      MYSQL_USER: sales_web_system
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ../db:/docker-entrypoint-initdb.d
    networks:
      - sales-web-system

  nginx_api:
    image: nginx:latest
    container_name: sales-web-system-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ../sales-web-system-api:/var/www
      - ../sales-web-system-api/nginx:/etc/nginx/conf.d
    networks:
      - sales-web-system

  app_client:
    image: app-client
    build:
      context: ../sales-web-system-client
      dockerfile: Dockerfile
    container_name: app-client
    ports:
      - 8002:80

networks:
  sales-web-system:
    driver: bridge